### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by YANLIANG0905** [jeffsonyu/VTacO#1] opened 2023-05-31 10:47 UTC
![image](https://github.com/jeffsonyu/VTacO/assets/104112468/62a499b2-aff7-439d-830e-c12531f5a2d2)

**Comment by YANLIANG0905** [comment] 2023-05-31 11:59
![image](https://github.com/jeffsonyu/VTacO/assets/104112468/65914640-c185-4858-8503-9e8fcf2146f1)

**Comment by jeffsonyu** [comment] 2023-05-31 15:17
We have upload the **default.yaml** file in the correct path: **configs/default.yaml**. Thank you for noticing and apologies for our mistake!

**Comment by YANLIANG0905** [comment] 2023-06-01 05:59
![image](https://github.com/jeffsonyu/VTacO/assets/104112468/88afe600-ed00-42af-93c7-9178c974ae45)

Thank you for your appreciation. With our guidance, you were able to successfully run the program, but encountered a new error. After reviewing the relevant code, you discovered an issue with the dictionary. Not sure if it's a configuration problem.

**Comment by jeffsonyu** [comment] 2023-06-01 12:38
This problem is caused by Windows. Could you run your code on a linux system? We haven't test it on Windows. Thank you for noticing and we will add the description on README.md

**Comment by YANLIANG0905** [comment] 2023-06-04 00:27
python train.py configs/VTacO/VTacO_YCB.yaml
python train.py configs/VTacOH/VTacOH_YCB.yaml
No visualized results ，May I ask how to modify and add visualizationfile
![2023-06-04 08-29-08 的屏幕截图](https://github.com/jeffsonyu/VTacO/assets/104112468/02d0a196-75ab-4c93-8f0c-a656e9279c4a)
![2023-06-04 08-31-04 的屏幕截图](https://github.com/jeffsonyu/VTacO/assets/104112468/94edf61b-a1c6-4266-b691-f61fcacc4158)
What does this file open with

**Comment by jeffsonyu** [comment] 2023-06-04 04:35
Normally the visualization result is saved in the **vis** directory, and the number of iteration for every visualization can be modified in the config file with the variable **training/visualize_every**.

**Comment by jeffsonyu** [comment] 2023-07-03 05:18
Since no update on this issue, we close it.

**Closed as completed by jeffsonyu** 2023-07-03 05:18 UTC
